source "https://rubygems.org"
ruby "2.3.0"

gem "mail"
gem "twitter"
gem "twilio"
gem "aitch"
gem "dotenv"
gem "env_vars"
gem "i18n"
gem "redis"
gem "telegram_bot"
gem "noti"
gem "activesupport"
gem "pry-meta"
gem "sequel"
gem "pg"
gem 'albatross-admin-client', git: 'https://github.com/XysInteratividade/albatross-admin-client.git', branch: 'master'
